apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "jf-prod-app-pr"
  namespace: argocd
spec:
  generators:
    - pullRequest:
        gitea:
          owner: "loft-demos"
          repo: "jf-prod-app"
          api: "https://github.com"
          insecure: true
          tokenRef:
            secretName: loft-demo-org-cred
            key: token
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "jf-prod-app-{{branch}}-pr{{number}}"
    spec:
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: "https://github.com/loft-demos/jf-prod-app.git"
        targetRevision: "{{head_sha}}"
        path: helm-chart/
        helm:
          parameters:
            - name: "image.repository"
              value: "ghcr.io/loft-demos/jf-prod-app-demo-app"
            - name: "image.tag"
              value: "{{head_short_sha}}"
            - name: "image.args.text"
              value: "Hello from jf-prod-app pr-{{number}} commit {{head_short_sha}}"
            - name: "ingress.hosts[0].host"
              value: "jf-prod-app-pr-{{number}}-jf-prod.us.demo.dev"
            - name: ingress.hosts[0].paths[0].backend.service.name
              value: juliet-app
            - name: ingress.hosts[0].paths[0].backend.service.port.name
              value: http
            - name: ingress.hosts[0].paths[0].path
              value: /
            - name: ingress.hosts[0].paths[0].pathType
              value: prefix
            - name: "ingress.tls[0].hosts[0]"
              value: "jf-prod-app-pr-{{number}}-jf-prod.us.demo.dev"
      project: "default"
      destination:
        server: "https://jf-prod.us.demo.dev/kubernetes/project/default/virtualcluster/jf-prod-app-pr-{{number}}"
        namespace: preview-hello-world-app
      info:
        - name: Preview App Link
          value: >-
            https://jf-prod-app-pr-{{number}}-jf-prod.us.demo.dev
        - name: Pull Request
          value: >-
            https://github.com/loft-demos/jf-prod-app/pulls/{{number}}
